spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/AmazonLike
    username: amazonlike
    password: admin
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
   port: 8080

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000
      